//
// Created by Nikita Krutoy on 28.06.2021.
//

#ifndef TESTOPENGLPROJECT_CAMERACONTROLLER_H
#define TESTOPENGLPROJECT_CAMERACONTROLLER_H


class CameraController {

};


#endif //TESTOPENGLPROJECT_CAMERACONTROLLER_H
